### ISSUE TITLE
Crash with seablock, when shift-right click a fluid machine followed by shift-left click an inserter

### ISSUE THREAD

**Issue by nanw1103** [billbo99/AdditionalPasteSettings#2]
The mod Additional Paste Settings (Fixed) (1.6.4) caused a non-recoverable error.Please report this error to the mod author.Error while running event AdditionalPasteSettings::additional-paste-settings-hotkey (ID 185)Unknown item name: liquid-molten-ironstack traceback:	[C]: in function 'set_filter'	__AdditionalPasteSettings__/smarts.lua:638: in function 'set_loader_filter'	__AdditionalPasteSettings__/smarts.lua:654: in function 'update_loader'	__AdditionalPasteSettings__/smarts.lua:659: in function 'act'	__AdditionalPasteSettings__/smarts.lua:749: in function <__AdditionalPasteSettings__/smarts.lua:732>

**Comment by Brilliand** [comment]
The error suggests that I copy-pasted a liquid-producing building onto a loader.  I tried doing that intentionally, and it _does_ reliably crash the game.

The first (accidental) crash happened when I was shift+dragging an upgrade planner in the vicinity of some loaders and buildings that produce liquid.  So while I wasn't intending to copy-paste any settings, I might have done so by accident.

**Comment by nanw1103** [comment]
Error while running event AdditionalPasteSettings::additional-paste-settings-hotkey (ID 185)Unknown item name: liquid-sulfuric-acid

**Comment by Brilliand** [comment]
The error doesn't happen with inserters; when you paste a building onto an inserter, it sets the inserter up to insert _into_ the building, and just leaves the inserter with no filters set if the building takes no solid inputs.

But pasting onto a loader apparently tries to set the loader up to output _from_ the building, and breaks if the building (only?) has fluid outputs.
