### ISSUE TITLE
Improve inserter filter pasting

### ISSUE THREAD

**Issue by mkaito** [billbo99/AdditionalPasteSettings#6]
Hi!

I'll put both feature requests in the same issue, hope that's okay.

- Add per-player setting to disable setting filters on inserters on paste.
- Filter on inserter should default to "any" quality instead of normal.

**Comment by billbo99** [comment]
Because all inserters are now filters this is a vanilla behavior with inserters.   
 - I can look at adding a player setting to clear filters when pasting.
 - Will take a look at the quality thing too

**Comment by billbo99** [comment]
<img width="107" alt="image" src="https://github.com/user-attachments/assets/24d44704-af70-4991-886c-8e7b964f6664">
Filters will set themselves to match the quality of the required ingredients.

A recipe will only accept the correct quality,  eg you cannot use common plates when the recipe wants epic plates.

**Comment by billbo99** [comment]
2.0.8
